feat: remove markdown links
googleapis/gapic-generator-typescript pull request #1004
Opened 2021-10-06 16:42 UTC by sofisl

Fixes #977

2021-10-06 17:47 UTC, summer-ji-eng requested changes
Try to understand what's the motivation of removing the markdown. Maybe I miss something in chat.

2021-10-06 17:47 UTC, summer-ji-eng commented on templates/typescript_samples/samples/generated/$version/_util.njk
> +{%- macro markDownStuff(formattedLine) %}
Could you rename `markDownStuff` to some name readable? 😆 
And looks like this method has not been used.

2021-10-06 17:47 UTC, summer-ji-eng commented on templates/typescript_samples/samples/generated/$version/_util.njk
> +{%- set regExp = r/\[(.*?)\]\(.*?\)/g -%}
This line is similar to line 32, is that possible we could reuse the regExp

2021-10-27 19:14 UTC, bcoe approved these changes
Left a nit, looks good to me in general though.

2021-10-28 14:08 UTC, fhinkel approved these changes
LGTM. Since this is all in JS files and not in TS comments, I think it's good this way.

2021-10-28 20:19 UTC, summer-ji-eng approved these changes

2021-10-28 23:29 UTC, merged