fix: naming collision on samples
googleapis/gapic-generator-typescript pull request #1034
Opened 2021-10-29 00:17 UTC by sofisl

Fixes #1000

2021-10-29 16:42 UTC, fhinkel approved these changes

2021-10-29 22:53 UTC, summer-ji-eng approved these changes

2021-11-01 17:09 UTC, alexander-fenster approved these changes

2021-11-03 18:50 UTC, bcoe commented
What if rather than `innerFunctionName`, we went with `callFunctoinName`, `inner` seemed slightly weird to me because it's actually the outer function from the perspective of an embeded sample.

2021-11-03 19:00 UTC, bcoe requested changes
See recommendations.

2021-11-03 20:04 UTC, bcoe approved these changes

2021-11-04 02:13 UTC, merged